// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Product struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Category  sql.NullString `json:"category"`
	Price     int32          `json:"price"`
	ImageUrl  sql.NullString `json:"image_url"`
	Rating    sql.NullString `json:"rating"`
	Reviews   sql.NullInt32  `json:"reviews"`
	IsOrganic sql.NullBool   `json:"is_organic"`
}
