// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	// Retrieves all products from the products table.
	GetAllProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
